name: Star

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "*/120 * * * *"   


permissions:
  contents: write

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Modify last update
        run: |
          echo "DATE $(date '+%Y-%m-%d %H:%M:%S')" > LOG

      - name: Commit
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add LOG
          msgs=("LOG" "Updated LOG" "Refresh LOG" "Auto commit LOG" "Heartbeat" "Tick" "Time update" "Cron 10m")
          git commit -m "${msgs[$((RANDOM % ${#msgs[@]}))]}" || echo "Nothing to commit"

      - name: Push
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # dùng GITHUB_TOKEN để auth và push về chính repo này
          git pull --rebase origin main || true
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git"
          git push origin HEAD:main
